version: '3.8'

services:
  # 1. PostgreSQL Database Service
  postgres:
    image: postgres:16-alpine
    container_name: asset-postgres
    restart: always
    environment:
      POSTGRES_DB: asset_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      # Mapping Host Port 5437 -> Container Internal Port 5432
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asset_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Go (Gin) Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: asset-backend
    restart: always
    environment:
      # Di dalam jaringan Docker, backend terhubung langsung ke service postgres port 5432
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: asset_db
      PORT: 8080
      # Google / Gmail SMTP Email Configuration
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_EMAIL: ${SMTP_EMAIL:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      APP_URL: ${APP_URL:-https://system-samba.my.id}
      APP_NAME: "SAMBA Asset Management"
    ports:
      # Mapping Host Port 8088 -> Container Internal Port 8080
      - "8088:8080"
    depends_on:
      postgres:
        condition: service_healthy

  # 3. React (Nginx) Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asset-frontend
    restart: always
    ports:
      # Mapping Host Port 3002 -> Container Internal Port 80
      - "3002:80"
    depends_on:
      - backend

  # 4. Cloudflare Tunnel Service (Auto connects domain system-samba.my.id)
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: asset-cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiNjg2ODcwZWMxNTVjMDQ2ZWU5MjE0OGIwZmQ3YWI2NWYiLCJ0IjoiNmFlNjRhN2YtNzBlZi00NjUwLTg5YmYtYmVhMWUyMzVlODFjIiwicyI6Ik16azJZamRrWVRJdE5qWmlZeTAwTURBNUxXRXpaRGN0TXpoa09XTTBObVptTTJFeiJ9
    depends_on:
      - frontend

volumes:
  postgres_data:

